[package]
name = "voronoice-inspector"
version = "0.0.1"
authors = ["Andre Esteve <andreesteve@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.4.0"
rand = "0.8.1"
voronoice = { path = "../voronoice", version = "0.0.1" }

[profile.dev.package."*"]
opt-level = 3
