[package]
name = "voronoice-inspector"
version = "0.0.2"
authors = ["Andre Esteve <andreesteve@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.1"
bevy = { version = "0.5.0", features = ["dynamic"] }
voronoice = { path = "../voronoice" }

[profile.dev.package."*"]
opt-level = 3
